apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-user
  namespace: keycloak
  labels:
    app: keycloak
    component: keycloak
type: Opaque
data:
  # password for admin web-interface `keycloak`
  password: a2V5Y2xvYWs=

