apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-watcher
  namespace: mastodon-watcher
  labels:
    app.kubernetes.io/name: mastodon-watcher
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mastodon-watcher
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mastodon-watcher
    spec:
      containers:
      - name: mastodon-watcher
        image: mastodon-watcher:0.1.0
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        ports:
        - containerPort: 6379
