kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: sample-app
  namespace: monitoring
  labels:
    app: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  namespaceSelector:
    matchNames:
    - default
  endpoints: 
  - port: http
